services:
  web:
    container_name: docker-k14-web-v1
    #    image: docker-k14-web
    build:
      context: .
      dockerfile: Dockerfile
    #    image: node:24-alpine3.21
    working_dir: /app/web
    volumes:
      - './web:/app/web'
    ports:
      - 5100:5173
    command:
      - npm
      - run
      - dev

  next:
    container_name: docker-k14-next-v1
    image: node:24-alpine3.21
    working_dir: /app/next
    volumes:
      - './next:/app/next'
    ports:
      - 3000:3000
    command: ['npm', 'run', 'dev']

  db:
    container_name: docker-k14-db-v1
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: default
    ports:
      - 5000:5432
    volumes:
      - ./db:/var/lib/postgresql/data

  api:
    image: node:24-alpine3.21
    command:
      - npx
      - json-server
      - db.json